### ISSUE TITLE
register NegotiationServiceProvider error in sliex 2.1

### ISSUE THREAD

**Issue by lcp0578** [K-Phoen/NegotiationServiceProvider#4]
```
ClassNotFoundException in NegotiationServiceProvider.php line 22:
Attempted to load interface "ServiceProviderInterface" from namespace "Silex".
Did you forget a "use" statement for "Pimple\ServiceProviderInterface"?
```
so, i add
` use Pimple\ServiceProviderInterface;`
but,again another mistake
```
FatalErrorException in NegotiationServiceProvider.php line 9:
Compile Error: Cannot use Pimple\ServiceProviderInterface as ServiceProviderInterface because the name is already in use
```
help me,thanks

**Comment by K-Phoen** [comment]
This service provider as been developed for Silex 1.x and has not been tested against Silex 2.x.

In fact, this project hasn't received any update for 2 years and is now considered as deprecated/unmaintained. This project should therefore NOT be used.

For these reasons, I'm sorry to announce you that I won't help you with your issue.
